apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-ds
  namespace: default
  labels:
    app: demo-ds
    component: test
  annotations:
    app: demo-ds
    app-anno: demo-ds
spec:
  selector:
    matchLabels:
      name: demo-ds
  template:
    metadata:
      labels:
        name: demo-ds
        component: test
      annotations:
        kiam.uswitch/component: agent
    spec:
      terminationGracePeriodSeconds: 0
      tolerations:
      - key: "nidhogg.uswitch.com/default"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nidhogg.uswitch.com/default.demo-ds"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: k3d-test-agent-0
      containers:
      - name: demo-ds
        # It runs the app.py script, which implemented a HTTP service listenning 8000 port
        image: registry:5000/demo:1
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      - name: sidecar
        # use this container to curl python app running in main container
        image: registry:5000/python:3.11.4
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
          requests:
            cpu: 10m
            memory: 10Mi
        command:
          - "/bin/bash"
          - "-c"
          - |
            sleep infinity
