apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetaint
spec:
  selector:
    matchLabels:
      app: nodetaint
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nodetaint
    spec:
      serviceAccountName: nodetaint
      terminationGracePeriodSeconds: 0
      tolerations:
      - key: "agent.kiam.uswitch/not-ready"
        operator: "Equal"
        value: "1"
        effect: "NoExecute"
      nodeSelector:
        kubernetes.io/hostname: k3d-test-agent-0
      containers:
      - name: nodetaint
        # image: quay.io/wish/nodetaint:v0.0.4
        image: registry:5000/nodetaint:v0.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        command:
        - /root/nodetaint
        args:
        - --log-level=debug
        - --node-taint="kiam.uswitch/agent-not-ready=1:NoExecute"
        - --daemonset-annotation=kiam.uswitch/component=agent
        ports:
        - containerPort: 9797
