apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetaint
spec:
  selector:
    matchLabels:
      app: nodetaint
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nodetaint
    spec:
      serviceAccountName: nodetaint
      terminationGracePeriodSeconds: 0
      tolerations:
      - key: "kiam.uswitch/agent-not-ready"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "nidhogg.uswitch.com/default.demo-ds"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: k3d-test-agent-0
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: config
      containers:
      - name: nidhogg
      # image: quay.io/uswitch/nidhogg:v0.4.0
        image: registry:5000/nidhogg:v0.4.0
        command:
        - /manager
        args:
         - --config-file=/config/config.json
         - --leader-election
         - --leader-configmap=nidhogg-election
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.json: |
     {
       "nodeSelector": [
         "kubernetes.io/hostname=k3d-test-agent-0"
       ],
       "daemonsets": [
         {
           "name": "demo-ds",
           "namespace": "default"
         }
       ]
     }

